import Head from "next/head";
import Image from "next/Image";
import Header from "../components/Header";
import { API_KEY, CONTEXT_KEY } from "../keys";
import Response from "../Response";
import { useRouter } from "next/dist/client/router";
import SearchReasults from "../components/SearchReasults";

function Search({results}) {
  const router = useRouter();

  
  return (
    <div>
      <Head>
        <title>{router.query.term} Search Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* search results */}
      <SearchReasults results={results}/>

    </div>
  );
}

export default Search;

export async function getServerSideProps(context) {
  const DummyData = true;
  const startIndex = context.query.start || "0";

  const data = DummyData
    ? Response
    : await fetch(
        `https://www.googleapis.com/customsearch/v1?key=${API_KEY}&cx=${CONTEXT_KEY}&q=${context.query.term}&start=${startIndex}`
      ).then((response) => response.json());
  return {
    props: {
      results: data,
    },
  };
}
